### ISSUE TITLE
Acquisition speed problem

### ISSUE THREAD

**Issue by hupozhao** [wollewald/ADS1220_WE#3]
I set the sensor to continuous mode, and then collected data. I found that the speed of the sensor is very slow, and it can only collect 30 times per second，How to improve the acquisition speed? For example, collect data 100 times per second?

**Comment by wollewald** [comment]
Hi @hupozhao ,

I was able to achieve almost 2000 SPS. I have described it in the tutorial:

https://wolles-elektronikkiste.de/en/4-channel-24-bit-adc-ads1220

Did you use Serial.println() to display the values? Then this is the bottleneck, because it is very slow.

**Comment by hupozhao** [comment]
Thank you for reading

Serial port output is really slow, and level 6 SPS has been set.

I now directly read ADS1220 data and write it into SPIFFS.

Currently, only 30 values can be written per second.

I am trying to use different settings to improve the reading speed.

Do you have any good suggestions?

thank you!

**Comment by wollewald** [comment]
Level 6 is good. Moreover you should use the continuous mode and the turbo mode. I have described this in my tutorial. You need to find the bottleneck. First you could try to just read let's say 2000 values without saving them. You can measure the time needed to get the values using millis(). You may need to do something with the values like adding them or so - otherwise the compiler might eliminate the sampling. As I wrote before I was able to get 2000 values in 1034 ms which is what it should deliver.
In a next step I would try to save 2000 float values on the SPIFFS. So no measured values, but just any values. 
Then you see what is the bottleneck. If both processes should be fast then it's something with the the combination of these processes. That's how I would analyse the issue.
You could also publish your code here or send it to me (wolfgang.ewald@wolles-elektronikkiste.de). Then I can have a look in the evening.

**Comment by wollewald** [comment]
Hi @hupozhao ,

I have taken your code snippets and have made the small program below out of it: 

````
#include <ADS1220_WE.h>
#include <SPI.h>

#define ADS1220_CS_PIN 5
#define ADS1220_DRDY_PIN 21

ADS1220_WE ads = ADS1220_WE(ADS1220_CS_PIN, ADS1220_DRDY_PIN);

void setup()
{
  ads_Begin();
  Serial.begin(115200);
  ads.setConversionMode(ADS1220_CONTINUOUS);
  ads.setOperatingMode(ADS1220_TURBO_MODE );
  ads.setDataRate(ADS1220_DR_LVL_6);
  ads.bypassPGA(true); 
  delay(1000);
   
  String result = "";
  unsigned long startingTime = millis();
  for(int i=0; i<1000;i++)
  {
    result = ads_Data();
  }
  unsigned long durationTime = millis() - startingTime;
  Serial.println(durationTime);
  Serial.println(result); // just to check
}

void loop(){}

void ads_Begin()
{
  if (!ads.init())
  {
    Serial.println("ADS1220 is not connected!");
    while (1) ;
  }
}

String ads_Data()
{
  ads.setCompareChannels(ADS1220_MUX_0_1); 
  float adata = ads.getVoltage_mV();
  
  ads.setCompareChannels(ADS1220_MUX_2_3); 
  float bdata = ads.getVoltage_mV();
  
  return String(adata, 5) + "," + String(bdata, 5);
}
````
The only relevant parts I changed were:
* I chose GPIO5  as CS, because my ESP32 did not like it when I took the GPIO12
* I changed to level 6
* I added code to measure the time needed for 1000 times performing ads_Data() which equals 2000 measurements. 

The time needed (durationTime) was 1290 milliseconds. This is only a bit slower than the maximum data rate, which would be 1000 milliseconds for 2000 measurements. The reason is the time needed for changing channels and all SPI communication.

However, this is much faster than the 30 measurements per seconds that you have found. The bottleneck must be somewhere else in the rest of your code. At least it's not related with the ADS1220 or the library. I recommend to do similar measurements for the other processes in your code. You said you write the results to the SPIFFS. I don't have much experience with SPIFFS, but I know from writing to SD cards that it slows down very much if you open and close the file every time when you write to it . Could it be something like that?

**Comment by hupozhao** [comment]
Thank you for reading @wollewald 
The chip I used is ESP32S3. I tested ADS1220 and ADXL355 respectively with the code you gave me. Here is the result:

ADS1220_durationTime:28749
ADS1220_result:-0.10425,0.03394
Failed to obtain time
Device found
ADXL355Started
ADXL355_durationTime:2062
ADXL355_result:0.01313,0.00010,1.00263


I just used the pin：
#define ADS1220_CS_PIN 12
#define ADS1220_DRDY_PIN 21
#define MISO 13
#define MOSI 14
#define SCLK 11
#define SS 12

My hardware has been designed, is my problem with GPIO?

**Comment by wollewald** [comment]
Hi @hupozhao ,

I had problems using GPIO12 as chip select pin and used GPIO5. Maybe you want to try that?

**Comment by hupozhao** [comment]
My hardware has been made, so I can't adjust GPIO.I try to add ADS1220_ CS_ PIN, always set to low level.

**Comment by hupozhao** [comment]
@wollewald I'll try flying line test GPIO5

**Comment by wollewald** [comment]
Exactly - and good idea to try it at least provisionally. Unfortunately I do not have an ESP32 S3 board available,  otherwise I would test it. Good luck!

**Comment by wollewald** [comment]
Since there was no further feedback I close the issue.
